#Configuration file for clouddb_extractor utilities
default_extractor : "bigquery"
sample_rows : 1000 # How many rows to extract when using load_sample to preview a table
tableau_env: #Tableau environment configuration defaults
  server_address : "https://eu-west-1a.online.tableau.com/" # The address of target Tableau Server or Tableau Online
  site_id : "testsiteid" # This corresponds to the contentUrl attribute in the Tableau REST API.
  project : "HyperAPITests" # The default Tableau project to store extract datasources
bigquery: #BigQueryExtractor configuration defaults
  staging_bucket : "HyperAPITestStaging" # Cloud blob storage bucket for extract staging if required
postgres: #PostgreSQL configuration defaults
  connection:
    dbname : "dev"
    user : "test"
    password : "password"
    host : "postgres.test"
    port : 5432
mysql: #Mysql configuration defaults
  connection:
    host : "mysql.test"
    database : "dev"
    port : 3306
    username : "test"
    #Recommended: use key vault instead of password
    #key_vault_url : "https://<your_keyvault_name>.vault.azure.net"
    #secret_name : my-password-secret
    password : "password"
    raise_on_warnings : True
azuresql: #Azure SQL Database configuration defaults
  connection:
    host : "mydbserver.test"
    port : 1433
    database : "test"
    username : "test"
    password : "password"
    connect_str_suffix : "Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30"
    raise_on_warnings : True
redshift: #Redshift configuration defaults
  connection:
    host : 'redshift-cluster-1.XXX.eu-west-1.redshift.amazonaws.com'
    database : 'dev'
    user : 'test'
    password : 'password'